apiVersion: v1
kind: Service
metadata:
  #name: auth-svc
  namespace: web-apps-v1
  name: authentication-app
spec:
  selector:
    app: auth-pod-v2
  ports:
    - name: port-8080
      protocol: TCP
      port: 8080
  type: NodePort
