apiVersion: v1
kind: Service
metadata:
  #name: auth-svc
  namespace: multiple
  name: auth-pod-v2
spec:
  selector:
    app: auth-pod-v2
  ports:
    - name: port-8080
      protocol: TCP
      port: 8080
  type: NodePort
