apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-pod-v2
  namespace: multiple
data:
  management.endpoints.web.exposure.include: health,metrics,httptrace,prometheus
  ROOT_PASSWORD_AUTH: cm9vdEAxMjM=
  ROOT_PASSWORD_NOTIFY: cm9vdEAxMjM=
  ROOT_PASSWORD_MONGO: ZXhhbXBsZQ==
  ADMIN_PASSWORD_ACTIVEMQ: YWRtaW4=
